# i = 0
# g = 1
# while i < 100:
#     print(i, " - even")
#     i = i + 2
#     print(g, " - odd")
#     g = g + 2
# print("finished")


print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")
print("1 კენტი")
print("2 ლუწი")


